# Generated by Django 4.1.3 on 2022-11-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscribers_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='email',
            new_name='user',
        ),
    ]
