# Generated by Django 4.1.3 on 2022-11-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_email_subscribers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='user',
        ),
        migrations.AddField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='Email'),
        ),
        migrations.CreateModel(
            name='SubLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование списка рассылки')),
                ('subscribers', models.ManyToManyField(to='users.subscribers', verbose_name='Подписчики')),
            ],
            options={
                'verbose_name': 'Список рассылки',
                'verbose_name_plural': 'Списки рассылки',
            },
        ),
    ]
