# Generated by Django 4.1.3 on 2022-11-15 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscribers_user_subscribers_email_sublists'),
    ]

    operations = [
        migrations.AddField(
            model_name='sublists',
            name='file',
            field=models.FileField(default=None, upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='Файл со списком рассылки'),
        ),
    ]
