# Generated by Django 4.1.3 on 2022-11-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_sublists_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True, verbose_name='Email'),
        ),
    ]
