# Generated by Django 4.1.3 on 2022-11-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingtemplates',
            options={'verbose_name': 'Макет рассылки', 'verbose_name_plural': 'Макеты рассылки'},
        ),
        migrations.AlterField(
            model_name='mailingtemplates',
            name='html',
            field=models.TextField(max_length=100000, verbose_name='Код макета'),
        ),
    ]
