# Generated by Django 4.1.3 on 2022-11-16 03:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0003_alter_mailingtemplates_name'),
        ('users', '0006_alter_sublists_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название рассылки')),
                ('now', models.BooleanField(default=True, verbose_name='Рассылка писем сейчас')),
                ('time_mail', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время рассылки писем')),
                ('sublist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='users.sublists', verbose_name='Список рассылки')),
                ('template', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='templates.mailingtemplates', verbose_name='Макет письма рассылки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
