# Generated by Django 4.1.3 on 2022-11-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailings',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
